export const infoObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About',
    headLine: 'About Me',
    description: 'blah blah blah',
    buttonLabel: 'Say Hello',
    imgStart: true,
    img: require('../../images/Jael.JPG').default,
    alt: 'Me',
    dark: true,
    primary: false,
    darkText: false,
    imgBig: true,
}

export const infoObjTwo = {
    id: 'contact',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Contact',
    headLine: 'Contact Me',
    description: 'blah blah blah',
    buttonLabel: 'Say Hello',
    imgStart: false,
    img: require('../../images/contact.svg').default,
    alt: 'Contact',
    dark: true,
    primary: false,
    darkText: false,
    imgBig: false,
}