export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About',
    headLine: 'About Me',
    description: 'blah blah blah',
    buttonLabel: 'Say Hello',
    imgStart: false,
    img: require('../../images/1.png'),
    alt: 'Me',
    dark: true,
    primary: false,
    darkText: false,
}